# Generated by Django 3.2.20 on 2023-09-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test9', models.CharField(max_length=255)),
                ('test8', models.DecimalField(decimal_places=10, max_digits=30)),
                ('test7', models.BigIntegerField()),
            ],
        ),
    ]
